Feature/vop 725 system status module
Biblioteksvagten/biblioteksvagten.dk pull request #3
Opened 2017-08-31 11:14 UTC by CarstenHoyer

https://reload.atlassian.net/browse/VOP-725

2017-08-31 11:46 UTC, googletorp commented
@CarstenHoyer  Drupal 8 modul til Drupal 7 site eller er det mig der er blind her?

2017-08-31 13:14 UTC, CarstenHoyer commented
@googletorp Fuck. Tak.

2017-08-31 13:54 UTC, CarstenHoyer commented
Det er rettet, så modulet nu er D7.

2017-08-31 14:02 UTC, googletorp requested changes
@CarstenHoyer 

Du bør tilføje modulet i vopros.make filen. Personligt vil jeg mene at update_hooken skal leve i profilen i stedet for vorpos_base modulet, men vopros_base er også ok.

2017-09-01 06:04 UTC, xendk commented
Jae, joe... Nu er det jo en tilføjelse til bibvagten, ikke til Vopros generelt. Men det er også lidt en moot point, for Vopros projektet (som i spørgetjenesten separat fra Biblioteksvagten) er rimeligt dødt...

2017-09-06 06:56 UTC, merged